#ifndef STORAGE_NVS_LOCAL_EXAMPLE_H
#define STORAGE_NVS_LOCAL_EXAMPLE_H

/*
 * 复制本文件为 storage_nvs_local.h 后，填写你自己的本地配置。
 * storage_nvs_local.h 已加入 .gitignore，不会提交到仓库。
 */

#define APP_DEFAULT_WIFI_SSID "YOUR_WIFI_SSID"
#define APP_DEFAULT_WIFI_PASSWORD "YOUR_WIFI_PASSWORD"
#define APP_DEFAULT_MQTT_HOST "broker.emqx.io"
#define APP_DEFAULT_MQTT_PORT 8883
#define APP_DEFAULT_MQTT_USE_TLS true
#define APP_DEFAULT_MQTT_USERNAME ""
#define APP_DEFAULT_MQTT_PASSWORD ""
#define APP_DEFAULT_DEVICE_ID "esp32_gateway_001"
#define APP_DEFAULT_API_TOKEN "esp32_001"
#define APP_DEFAULT_SAMPLE_PERIOD_MS 2000
#define APP_DEFAULT_MODBUS_ENABLED false
#define APP_DEFAULT_MODBUS_SLAVE_ADDR 1
#define APP_DEFAULT_MODBUS_BAUD_RATE 9600
#define APP_DEFAULT_MODBUS_START_REGISTER 0
#define APP_DEFAULT_MODBUS_REGISTER_COUNT 4
#define APP_DEFAULT_MODBUS_POLL_PERIOD_MS 5000

#endif
